### ISSUE TITLE
Allow for enabling LetsEncrypt on an app

### ISSUE THREAD

**Issue by jvanbaarsen** [intercity/intercity-next#48]
this way we can enable SSL by default! :tada: 
See: https://github.com/dokku/dokku-letsencrypt

**Comment by jvanbaarsen** [comment]
Played around with Letsencrypt and the Dokku-Letsencrypt plugin, it feels to brittle to be in an automated production app at the moment.

I really want to have this feature, but we have to postpone the implementation to a little later on.

I'll remove the current Milestone, and reopen #24

**Comment by josegonzalez** [comment]
What is brittle about the plugin?

**Comment by jvanbaarsen** [comment]
@josegonzalez It's mainly in the way that we are using it. The plugin itself works properly, but since we are an automated system that does everything via a web-interface, and thus cannot 100% make sure that all domains for all apps are working, the plugin broke down a lot of times (Because of wrong domains).

Another issue is the rate limiting that Let's Encrypt is using, and that is not something the plugin is to blame for!

**Comment by josegonzalez** [comment]
Can you expand on "wrong domains" being an issue? Seems like something you might be able to check by grabbing all the domains for an app and then doing like "this one is good, this one is bad" and only enabling for known good domains.

**Comment by jvanbaarsen** [comment]
@josegonzalez It's mainly about domains that might not be reachable for LE to perform their validation. The downside of the plugin is that you can't enable LE for just one domain, it is only possible to enable it for an entire app.

**Comment by michiels** [comment]
I think using the plugin is still the way to go. But yes, we need to take into account that *all* domains added to the app should be LetsEncryptable, otherwise automated renews will break.

However, if we add a more thorough logging mechanism so we can pull execution logs and errors from Dokku, we could at least indicate to the user that they should fix a domain.

**Comment by michiels** [comment]
I've had a couple starter ideas for this. I think we can start out with adding a widget to the "Domains" page where you can enable/disable the LetsEncrypt plugin for the app and we can show a little warning to the users so that they realize DNS records need to be set up before LetsEncrypting domains to work.

<img width="1347" alt="schermafbeelding 2018-11-22 om 21 32 11" src="https://user-images.githubusercontent.com/42268/48921213-7fbaeb80-ee9e-11e8-9cf0-d1a255bbe049.png">

In addition we can add a "refresh LetsEncrypt" button, when the user adds a new domain to their list and would like to recertify the added domain.

**Comment by manzu** [comment]
Hi, @michiels, how is this going? I'm looking to use this for my personal setup

**Comment by michiels** [comment]
Hi @manzu. Saw your comment from February. An initial LetsEncrypt implementation is in master of this repository. It is quite usable already! And will use the dokku-letsencrypt plugin to manage things under the hood.
